services:
  - type: web
    name: ignivance-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /share-your-story
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html